kind: pipeline
type: docker
name: default

steps:
- name: build
  image: node
  commands:
  - npm install
  - npm run test
  - npm run build
- name: docker  
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: rfjbraunstingl/just-write
    tags: latest
- name: deploy
  image: appleboy/drone-jenkins
  settings:
    url: https://jenkins.mangi.app
    user: jenkins
    token:
      from_secret: jenkins_token
    job: Deployment/just-write.rfj.dev
