kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: node
    commands:
      - npm install
      - # (currently, there are no tests) npm test -- --watchAll=false
      - npm run build

  - name: docker
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: rfjbraunstingl/just-write
      tags:
        - latest
        - ${DRONE_COMMIT}
      steps:

  - name: prepare-k8s-yml
    image: alpine:latest
    commands:
      - sed -i 's/container-tag/$DRONE_COMMIT/g' input.txt

  - name: deploy
    image: bitnami/kubectl:latest
    environment:
      RFJ_K8S_SERVER:
        from_secret: k8s_server_prod
      RFJ_K8S_TOKEN:
        from_secret: k8s_token_prod
    commands:
      - kubectl apply -f kubernetes.yml --namespace production --server $RFJ_K8S_SERVER --insecure-skip-tls-verify --token $RFJ_K8S_TOKEN
