---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: just-write
  name: just-write
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app.kubernetes.io/name: just-write
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: just-write
  name: homechefs-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: just-write
  template:
    metadata:
      labels:
        app.kubernetes.io/name: just-write
    spec:
      containers:
      - image: rfjbraunstingl/just-write:latest
        imagePullPolicy: Always
        name: just-write
        ports:
          - containerPort: 80
            name: http
            protocol: TCP
